### ISSUE TITLE
Measure sentiment for Code for Life on social media 

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/codeforlife-deploy-appengine#109]
Currently, we use Hootsuite for his data. However, it doesn't seem to be very accurate showing positive comments as neutral. 

Can we create or use another API for this? 

We will need the API for Twitter and Facebook

**Comment by jonathon-read** [comment]
### Initial things to do
- Use Twitter API to download mentions of @codeforlifeuk
- Evaluate options for sentiment classification (Google, CoreNLP, embeddings, dictionary) 
- Find platform for automated job and reporting.

Could be quite hard for machine learning, e.g.:

> During Computing today, Year 2 Toucans learned about creating algorithms and then debugging parts of a code which don’t work as intended.

Perhaps we could have some heuristics as a prefilter (e.g. if it contains the word 'learn' we might be pretty confident it's positive).

**Comment by mrniket** [comment]
Not a priority right now, closing (will reopen later if needed).
