### ISSUE TITLE
Create curriculum summary for Bett Show

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/codeforlife-deploy-appengine#137]
Based on the current introduction to coding document:
https://storage.googleapis.com/codeforlife-assets/general_resources/introduction_to_coding.pdf

Use tick boxes to show how Rapid Router relates to the English and Welsh National curriculum

**Comment by rdcruzCFL** [comment]
I have created a document https://drive.google.com/open?id=1dV_3mFltpXulGAlEIFQn1Z975pWixGOPx-OWMmkyX5A that shows which of the National Curriculum (England) Computing points are met by Rapid Router

**Comment by j4mesholland** [comment]
Ive branded this in the Code for Life style. Please review:[https://app.zenhub.com/files/49142916/57deb35e-46e9-4471-a9e1-6557fe4de3e6/download](https://app.zenhub.com/files/49142916/57deb35e-46e9-4471-a9e1-6557fe4de3e6/download)

**Comment by faucomte97** [comment]
Looks great :)
