### ISSUE TITLE
Understand differences in National and Scottish curriculum

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/codeforlife-deploy-appengine#138]
- Review both curriculums and identify the differences
- Make suggestions for overcoming differences
- Think about how we could tie into the general worldwide curriculums

**Comment by rdcruzCFL** [comment]
Work in progress: https://docs.google.com/document/d/1ujx59b72MPb5C2QV6sn0ECfVItMQebRYGtLLNUW8gC4/edit

**Comment by rdcruzCFL** [comment]
This is complete now subject to review. 

This is the starting point:
https://docs.google.com/document/d/1dV_3mFltpXulGAlEIFQn1Z975pWixGOPx-OWMmkyX5A/

This links to:
https://docs.google.com/document/d/1ujx59b72MPb5C2QV6sn0ECfVItMQebRYGtLLNUW8gC4/
and
https://docs.google.com/spreadsheets/d/1GCBMYWhWGx-8JVZ9bfDsoCp75wVXdKkUDExKyF5C2ac/edit#gid=1422941617

I have asked for local input and will feedback if I get any.

**Comment by j4mesholland** [comment]
This is great stuff @rdcruzCFL, thank you! I suppose the next step would be to distil this into a Scottish Curriculum version of this https://storage.googleapis.com/codeforlife-assets/general_resources/introduction_to_coding.pdf document

**Comment by rdcruzCFL** [comment]
Yes, that would make sense. I would like to get some feedback from a teacher in Scotland first. I don't think I have misunderstood but it is important that we check that!

If I don't hear from the general post, I will try to target someone directly.

**Comment by j4mesholland** [comment]
Yes, once this has been fully reviewed I will create a sperate task for the Scottish version of the 'Introduction to coding' document

**Comment by rdcruzCFL** [comment]
I have a reply now from a Scottish teacher on CAS. The only other Experiences & Outcome (Es&O) he suggested wasn't relevant to Rapid Router as it was to do with choosing development tools. He suggested this document which I have now added as a link in the Scottish National Curriculum Google doc: An overview of the purpose of the benchmarks: https://education.gov.scot/improvement/learning-resources/curriculum%20for%20excellence%20benchmarks
