### ISSUE TITLE
Flyer for Bett show - outline text

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/codeforlife-deploy-appengine#139]
## Description
- An outline with the benefits of using Rapid Router in schools
- Add some teacher testimonials
- Emphasise that the game and resources are FREE, and how we are sponsored

**Comment by rdcruzCFL** [comment]
I created a Google drawing with some suggested text for the flyer. Let me know if you would like me to rework it.
https://drive.google.com/open?id=12D_toqfQffRJyVqbnUyK6oNGNROdroUJkHcJLcrAeOg

**Comment by j4mesholland** [comment]
@rdcruzCFL This looks good to me. I have linked this issue to the Artwork issue: 
https://app.zenhub.com/workspaces/code-for-life-team-56f2afba6e54555c586f6db3/issues/ocadotechnology/codeforlife-deploy-appengine/140
