### ISSUE TITLE
Create newsletter template for Dot Mailer emails

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/codeforlife-deploy-appengine#150]
# Description
We have now moved over from Mail Chimp to Dot Mailer and therefore a new email template will need to be created.
 
# Acceptance criteria
- Include Code for Life logo
- Must be responsive
- Include or legal and unsubscribe options

# Analytics
To review on Dot Mailer after each campaign

**Comment by j4mesholland** [comment]
I have created a responsive template on Dot Mailer. 
![Screen Shot 2019-02-21 at 14.24.19.png](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/27e38357-b011-4678-ba67-7c1b18e3192b)

**Comment by faucomte97** [comment]
Looks good to me :)
