### ISSUE TITLE
Upgrade from Django 2.0 -> 2.2

### ISSUE THREAD

**Issue by mrniket** [ocadotechnology/codeforlife-deploy-appengine#178]
### What's new in Django 2.1 and 2.2:
https://docs.djangoproject.com/en/2.2/releases/2.1/
https://docs.djangoproject.com/en/2.2/releases/2.2/

### List of backwards-incompatible changes:
https://docs.djangoproject.com/en/2.2/releases/2.1/#backwards-incompatible-changes-in-2-1
https://docs.djangoproject.com/en/2.2/releases/2.2/#backwards-incompatible-changes-in-2-2

This will require the Rapid Router, Portal and AIMMO repos to be upgraded to 2.2 before app engine can be upgraded

> **Needs to be tested on dev**

**Comment by faucomte97** [comment]
Closing this as we're updating directly from 1.11 to 2.2, cf #176.
