### ISSUE TITLE
Deployment occasionally fails because of SSL connection error

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/codeforlife-deploy-appengine#213]
**Describe the bug**
Upon deployment (to any server), the build occasionally fails on the `deploy.sh` command. The build raises a SSL connection error.
This has been an issue for a while but it can usually be bypassed by simply relaunching the build. It would be great to eradicate that issue though as it wastes a lot of time.
It looks like the error might have something to do with mysqlclient or something similar within Django.

**To Reproduce**
Steps to reproduce the behaviour:
The issue might be reproduced on a regular deployment build, but there are no set steps to purposefully trigger it.

**Expected behaviour**
The error shouldn't be raised and the deployment build should work without having to reschedule it.

**Screenshots**
![Selection_004.png](https://images.zenhubusercontent.com/5a0b05968a75884b90875e9b/139faf54-3c7f-4504-ab88-8a79ffe853f0)

**Comment by dionizh** [comment]
No more Semaphore 
(that rhymes!)
