### ISSUE TITLE
Discover Kubernetes

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-deploy-appengine#289]

**Comment by faucomte97** [comment]
We need to plan our update of Kubernetes to include the GCP recommendations we were given.

**Comment by faucomte97** [comment]
It looks like we might need to update the cluster resource we use in our main.tf file so we can enable the additional settings mentioned in the report. Cf https://registry.terraform.io/providers/hashicorp/google/3.14.0/docs/resources/container_cluster
