### ISSUE TITLE
Automatic deployment to staging in all 3 repos is broken

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/codeforlife-deploy-appengine#298]
Triggering automatic staging deployment job in GA workflows breaks because admin permissions are required.

cf https://github.com/ocadotechnology/aimmo/actions/runs/5056362817/jobs/9073774910 for example

**Comment by lauracumming** [comment]
Is this still a bug @faucomte97 Do we need to prioritise it to help flow?

**Comment by faucomte97** [comment]
@lauracumming Yes this is the razbot task
