### ISSUE TITLE
Version Control for design files

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/codeforlife-deploy-appengine#67]
We need to add an archive folder for all earlier designs. Only the most current designs should be outside this folder.

Or figure out a better way of working

**Comment by j4mesholland** [comment]
We need to decide on a tool for this...
https://kactus.io/ is free for public repository only and Mac only

What about @mariaFernando's files?

**Comment by mrniket** [comment]
It's possible just to use normal git for that... each time she commits it will make a copy of the file behind the scene. I can't think of a better way than that for now. It still beats a folder when files named "final final final version" or no version control

**Comment by j4mesholland** [comment]
Lets trial https://kactus.io/ starting next sprint
