### ISSUE TITLE
Organise lunch break volunteer session

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/codeforlife-deploy-appengine#82]

**Comment by j4mesholland** [comment]
@CelineBoudier We discussed at the Wednesday evening standup. We still need to agree on a date and format...

**Comment by j4mesholland** [comment]
Move to next sprint

**Comment by CelineBoudier** [comment]
the questionnaire has been sent
I'll create a new issue when we actually send the doodle link after
